windower.prim.create('TP_SET')
windower.prim.set_size('TP_SET',200,30)
windower.prim.set_texture('TP_SET','/windower 4/addons/gearswap/data/'..player.name..'/images/absorbmode.png')
windower.prim.set_position('TP_SET',750,50)
windower.prim.set_color('TP_SET', 100, 255, 255, 255)
windower.prim.set_visibility('TP_SET',true)

windower.prim.create('ACC_SET')
windower.prim.set_size('ACC_SET',200,30)
windower.prim.set_texture('ACC_SET','/windower 4/addons/gearswap/data/'..player.name..'/images/highacc.png')
windower.prim.set_position('ACC_SET',750,90)
windower.prim.set_color('ACC_SET', 100, 255, 255, 255)
windower.prim.set_visibility('ACC_SET',true)

windower.prim.create('IDLE_SET')
windower.prim.set_size('IDLE_SET',200,30)
windower.prim.set_texture('IDLE_SET','/windower 4/addons/gearswap/data/'..player.name..'/images/standardidle.png')
windower.prim.set_position('IDLE_SET',750,130)
windower.prim.set_color('IDLE_SET', 100, 255, 255, 255)
windower.prim.set_visibility('IDLE_SET',true)

windower.prim.create('WS_SET')
windower.prim.set_size('WS_SET',200,30)
windower.prim.set_texture('WS_SET','/windower 4/addons/gearswap/data/'..player.name..'/images/acc.png')
windower.prim.set_position('WS_SET',750,170)
windower.prim.set_color('WS_SET', 100, 255, 255, 255)
windower.prim.set_visibility('WS_SET',true)